[MTKA-1446] Fix blueprint import if zip file was renamed (#459)
* fix: use root zip folder when importing blueprints

So that a renamed zip file does not generate an import error:

```
> wp acm blueprint import http://contentmodel1.wpengine.com/wp-content/uploads/2022/03/acm-rabbits-4.zip
Fetching zip.
Unzipping.
Verifying ACM manifest.
Error: Could not read an acm.json file in the blueprint folder.
```

* docs: add changelog entry

* test: confirm renamed zips unzip correctly

* test: force-add test zip file